# Generated by Django 6.0.5 on 2026-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Checkin_date', models.DateField()),
                ('Reservation', models.CharField(choices=[('1', 'Bed only'), ('2', 'Bed and Breakfast'), ('3', 'Half board'), ('4', 'Full board'), ('5', 'Conference room')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_number', models.CharField(max_length=10)),
                ('Room_type', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
