# Generated by Django 6.0.5 on 2026-05-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='Checkin_date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='Reservation',
            new_name='Package',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='Contact',
            new_name='Phone',
        ),
    ]
